Add definition for Legal Entity Basic Information
Virtual-Finland/definitions pull request #2
Opened 2022-03-10 14:15 UTC by joakimnordling

- Rremoved defintion related to ioxio-nexus-guides

2022-03-10 14:31 UTC, lietu requested changes
I think we should improve on this still

2022-03-10 20:39 UTC, hsuomi commented on src/draft/LegalEntity/BasicInformation.py
> +class RegisteredAddress(CamelCaseModel):
I agree we could have those character limits no initially. That is a good proposal and we can continue improving those limits further based on the results and feedback in the experimentation.

2022-03-10 20:44 UTC, hsuomi commented on src/draft/LegalEntity/BasicInformation.py
> +class RegisteredAddress(CamelCaseModel):
I was the most pondering between the buildingNumber / buildingIdentifier. It seemed that for a registered address separate from visiting and postal addresses the buildingNumber would have been enough in the Scandinavian context but I agree we should change the buildingNumber property still.

2022-03-10 21:01 UTC, hsuomi requested changes

2022-03-10 21:01 UTC, hsuomi commented on DataProducts/draft/LegalEntity/BasicInformation.json
> +            "example": 34
54 A

2022-03-25 06:43 UTC, joakimnordling commented on src/draft/LegalEntity/BasicInformation.py
> +class LegalForm(str, Enum):
This is unfortunately not possible without changes to the tooling that is used to convert the definitions. I've suggested to create separate tasks for adding this support. Those changes should however be made all the way in the definitions template repo, not in this repo.

2022-03-25 06:44 UTC, joakimnordling commented on DataProducts/draft/LegalEntity/BasicInformation.json
> +          "buildingNumber": {
Changed.

2022-03-28 06:54 UTC, hsuomi approved these changes

2022-03-28 07:34 UTC, merged