Implement Employment EscoOccupations
Virtual-Finland/definitions pull request #48
Opened 2023-04-16 13:51 UTC by omarudolley

Implement Employment EscoOccupations definition

2023-04-17 07:01 UTC, hsuomi requested changes

2023-04-17 07:01 UTC, hsuomi commented on DataProducts/draft/Employment/EscoOccupations.json
> +            "description": "A list of relevant occupation classes based on ESCO standard"
The change has also been aligned in the spec and highlighted with red.

2023-04-17 09:19 UTC, hsuomi requested changes

2023-04-17 09:19 UTC, hsuomi commented on DataProducts/draft/Employment/EscoOccupations.json
> +            "maxLength": 40,
Job Title max length must be increased to 250 characters

2023-04-17 09:19 UTC, hsuomi commented on DataProducts/draft/Employment/EscoOccupations.json
> +            "maxLength": 250,
Let's remove the max length validation from ESCO description. They can occationally be rather long > 1000 characters.

2023-04-17 13:37 UTC, joakimnordling requested changes

2023-04-17 13:37 UTC, joakimnordling commented on src/draft/Employment/EscoOccupations.py
> +        title="ESCO codes",
```suggestion
        title="ESCO Code",
```

2023-04-18 06:58 UTC, hsuomi approved these changes

2023-04-18 07:26 UTC, joakimnordling approved these changes

2023-04-18 07:27 UTC, merged